### PR TITLE
Add FreeFlixMedia account to coral genesis

### PR DESCRIPTION
**Pull request by saiSunkari19**

### CODE REVIEW

**Review by ethanfrey — APPROVED** [review]
Welcome to coralnet! 

I'd love to see cosmiccompass.io support for this one day as well. (CoCo and FreeFlixMedia are the same group, right?)

**Comment by ethanfrey** [comment]
Manually rebased and merged due to merge conflicts.

Please verify that https://github.com/CosmWasm/testnets/commit/04e4099bf5c818e63d09511831933720a2697fc6 is the correct key

**Comment by svabhishek** [comment]
> Welcome to coralnet!
> 
> I'd love to see cosmiccompass.io support for this one day as well. (CoCo and FreeFlixMedia are the same group, right?)

Hi @ethanfrey - yes. The participation will cover our tests and experiments for both projects, CoCo & FreeFlix Media.

With FreeFlix Media, we aim to get creators/studios/agencies to compose contracts using the CoCo Contract Manager (a contract composing interface that's powered by CoCo).

Although not for the testnet phase, but as CoCo, we aim to develop a simple/neat drag-and-drop interface for composing & deploying Smart Contracts using CosmWasm on any Cosmos-based chain.

Thank You once again for looking forward to the participation. We will be sure to make the most out of this testnet period and contribute back to the community.

Cheers!

**Comment by ethanfrey** [comment]
> Although not for the testnet phase, but as CoCo, we aim to develop a simple/neat drag-and-drop interface for composing & deploying Smart Contracts using CosmWasm on any Cosmos-based chain.

Sounds amazing!

**Pull request closed without merging**
